services:
  
  stockify.api:
    image: ${DOCKER_REGISTRY-}stockify
    container_name: Stockify.API
    build:
      context: .
      dockerfile: src/API/Stockify.API/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
        
  stockify.seq:
    image: datalust/seq:latest
    container_name: Stockify.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
