services:
  
  stockify.api:
    image: ${DOCKER_REGISTRY-}stockify
    container_name: Stockify.API
    build:
      context: .
      dockerfile: src/API/Stockify.API/Dockerfile
    depends_on:
      - stockify.database
    ports:
      - 5050:8080
      - 5051:8081
        
  stockify.seq:
    image: datalust/seq:latest
    container_name: Stockify.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
        
  stockify.database:
    image: postgres:latest
    container_name: Stockify.Database
    environment:
      - POSTGRES_DB=stockify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  stockify.identity:
    image: quay.io/keycloak/keycloak:latest
    container_name: Stockify.Identity
    command: start-dev --import-realm
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files:/opt/keycloak/data/import
    ports:
      - 18080:8080