// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Stockify.Modules.Stocks.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class AddTickers : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "tickers",
                schema: "stocks",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    symbol = table.Column<string>(type: "character varying(5)", maxLength: 5, nullable: false),
                    name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    description = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
                    cik = table.Column<string>(type: "character varying(10)", maxLength: 10, nullable: false),
                    active = table.Column<bool>(type: "boolean", nullable: false),
                    ticker_type_id = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_tickers", x => x.id);
                    table.ForeignKey(
                        name: "fk_tickers_ticker_types_ticker_type_id",
                        column: x => x.ticker_type_id,
                        principalSchema: "stocks",
                        principalTable: "ticker_types",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_tickers_cik",
                schema: "stocks",
                table: "tickers",
                column: "cik",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_tickers_symbol",
                schema: "stocks",
                table: "tickers",
                column: "symbol",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_tickers_ticker_type_id",
                schema: "stocks",
                table: "tickers",
                column: "ticker_type_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "tickers",
                schema: "stocks");
        }
    }
}
