// <auto-generated/>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Stockify.Modules.Stocks.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class AddTickerSubscriptions : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "ticker_subscriptions",
                schema: "stocks",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    ticker_id = table.Column<Guid>(type: "uuid", nullable: false),
                    stockholder_id = table.Column<Guid>(type: "uuid", nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    active = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_ticker_subscriptions", x => x.id);
                    table.ForeignKey(
                        name: "fk_ticker_subscriptions_stockholders_stockholder_id",
                        column: x => x.stockholder_id,
                        principalSchema: "stocks",
                        principalTable: "stockholders",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_ticker_subscriptions_tickers_ticker_id",
                        column: x => x.ticker_id,
                        principalSchema: "stocks",
                        principalTable: "tickers",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_ticker_subscriptions_stockholder_id",
                schema: "stocks",
                table: "ticker_subscriptions",
                column: "stockholder_id");

            migrationBuilder.CreateIndex(
                name: "ix_ticker_subscriptions_ticker_id_stockholder_id",
                schema: "stocks",
                table: "ticker_subscriptions",
                columns: new[] { "ticker_id", "stockholder_id" },
                unique: true,
                filter: "active = true");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ticker_subscriptions",
                schema: "stocks");
        }
    }
}
