// <auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Stockify.Modules.Stocks.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class AddTickerIndex : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateIndex(
                name: "ix_tickers_symbol_name_description",
                schema: "stocks",
                table: "tickers",
                columns: new[] { "symbol", "name", "description" })
                .Annotation("Npgsql:IndexMethod", "GIN")
                .Annotation("Npgsql:TsVectorConfig", "english");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_tickers_symbol_name_description",
                schema: "stocks",
                table: "tickers");
        }
    }
}
