// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Stockify.Modules.Stocks.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class AddRiskProfile : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "attitude_type",
                schema: "stocks",
                table: "stockholders",
                type: "character varying(50)",
                maxLength: 50,
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "risk_coefficient",
                schema: "stocks",
                table: "stockholders",
                type: "numeric(18,4)",
                precision: 18,
                scale: 4,
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<DateTime>(
                name: "risk_profile_updated_at_utc",
                schema: "stocks",
                table: "stockholders",
                type: "timestamp with time zone",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "attitude_type",
                schema: "stocks",
                table: "stockholders");

            migrationBuilder.DropColumn(
                name: "risk_coefficient",
                schema: "stocks",
                table: "stockholders");

            migrationBuilder.DropColumn(
                name: "risk_profile_updated_at_utc",
                schema: "stocks",
                table: "stockholders");
        }
    }
}
