// <auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Stockify.Modules.Users.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class RenamedJoinEntitiesColumns : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "permissions_code",
                schema: "users",
                table: "role_permissions",
                newName: "permission_code");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "permission_code",
                schema: "users",
                table: "role_permissions",
                newName: "permissions_code");
        }
    }
}
