// <auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Stockify.Modules.Risks.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class AddIndividualRiskAttitude : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "max_points",
                schema: "risks",
                table: "sessions",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<decimal>(
                name: "risk_coefficient",
                schema: "risks",
                table: "individuals",
                type: "numeric(18,4)",
                precision: 18,
                scale: 4,
                nullable: false,
                defaultValue: 0m);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "max_points",
                schema: "risks",
                table: "sessions");

            migrationBuilder.DropColumn(
                name: "risk_coefficient",
                schema: "risks",
                table: "individuals");
        }
    }
}
