// <auto-generated/>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Stockify.Modules.Risks.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class AddSubmissionEntity : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "total_points",
                schema: "risks",
                table: "sessions",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.CreateTable(
                name: "submissions",
                schema: "risks",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    session_id = table.Column<Guid>(type: "uuid", nullable: false),
                    question_id = table.Column<Guid>(type: "uuid", nullable: false),
                    answer_id = table.Column<Guid>(type: "uuid", nullable: false),
                    points = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_submissions", x => x.id);
                    table.CheckConstraint("CK_Points_NotNegative", "points >= 0");
                    table.ForeignKey(
                        name: "fk_submissions_answers_answer_id",
                        column: x => x.answer_id,
                        principalSchema: "risks",
                        principalTable: "answers",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_submissions_questions_question_id",
                        column: x => x.question_id,
                        principalSchema: "risks",
                        principalTable: "questions",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_submissions_sessions_session_id",
                        column: x => x.session_id,
                        principalSchema: "risks",
                        principalTable: "sessions",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_submissions_answer_id",
                schema: "risks",
                table: "submissions",
                column: "answer_id");

            migrationBuilder.CreateIndex(
                name: "ix_submissions_question_id",
                schema: "risks",
                table: "submissions",
                column: "question_id");

            migrationBuilder.CreateIndex(
                name: "ix_submissions_session_id",
                schema: "risks",
                table: "submissions",
                column: "session_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "submissions",
                schema: "risks");

            migrationBuilder.DropColumn(
                name: "total_points",
                schema: "risks",
                table: "sessions");
        }
    }
}
